package GetterSetter;
// Generated Apr 2, 2015 11:20:49 PM by Hibernate Tools 4.3.1



/**
 * GS_Movie generated by hbm2java
 */
public class GS_Movie  implements java.io.Serializable {


     private int id;
     private String movid;
     private String name;
     private int year;
     private String plot;
     private String genre;
     private String cast;
     private String producer;
     private String director;

    
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getMovid() {
        return this.movid;
    }
    
    public void setMovid(String movid) {
        this.movid = movid;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public int getYear() {
        return this.year;
    }
    
    public void setYear(int year) {
        this.year = year;
    }
    public String getPlot() {
        return this.plot;
    }
    
    public void setPlot(String plot) {
        this.plot = plot;
    }
    public String getGenre() {
        return this.genre;
    }
    
    public void setGenre(String genre) {
        this.genre = genre;
    }
    public String getCast() {
        return this.cast;
    }
    
    public void setCast(String cast) {
        this.cast = cast;
    }
    public String getProducer() {
        return this.producer;
    }
    
    public void setProducer(String producer) {
        this.producer = producer;
    }
    public String getDirector() {
        return this.director;
    }
    
    public void setDirector(String director) {
        this.director = director;
    }




}


