package GetterSetter;
// Generated Apr 2, 2015 11:20:49 PM by Hibernate Tools 4.3.1



/**
 * GS_Reg generated by hbm2java
 */
public class GS_Reg  implements java.io.Serializable {


     private int id;
     private String userid;
     private String fname;
     private String lname;
     private String email;
     private String pswd;
     private String date;
     private String num;
     private int t;

    public GS_Reg() {
    }

    public GS_Reg(String userid, String fname, String lname, String email, String pswd, String date, String num, int t) {
       this.userid = userid;
       this.fname = fname;
       this.lname = lname;
       this.email = email;
       this.pswd = pswd;
       this.date = date;
       this.num = num;
       this.t = t;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getUserid() {
        return this.userid;
    }
    
    public void setUserid(String userid) {
        this.userid = userid;
    }
    public String getFname() {
        return this.fname;
    }
    
    public void setFname(String fname) {
        this.fname = fname;
    }
    public String getLname() {
        return this.lname;
    }
    
    public void setLname(String lname) {
        this.lname = lname;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPswd() {
        return this.pswd;
    }
    
    public void setPswd(String pswd) {
        this.pswd = pswd;
    }
    public String getDate() {
        return this.date;
    }
    
    public void setDate(String date) {
        this.date = date;
    }
    public String getNum() {
        return this.num;
    }
    
    public void setNum(String num) {
        this.num = num;
    }
    public int getT() {
        return this.t;
    }
    
    public void setT(int t) {
        this.t = t;
    }




}


